context:
  initializer:
    classes: io.github.carlomicieli.roundhouse.TestConfigInitializer

logging:
  level:
    org.springframework: INFO
    org.springframework.r2dbc: INFO
    org.springframework.web.reactive: INFO
    org.testcontainers: INFO
    io.github.carlomicieli.roundhouse: INFO
