spring:
    application:
        name: trenako
    lifecycle:
        timeout-per-shutdown-phase: 15s

server:
    port: 8080
    shutdown: graceful

logging:
    level:
        org.springframework: INFO
        com.trenako: DEBUG

management:
    server:
        port: 8081
    endpoints:
        enabled-by-default: false
        web:
            base-path: /
            exposure:
                include: health
    endpoint:
        health:
            enabled: true
