name: CI with Gradle
on:
  push:
    paths-ignore:
      - '.cz.toml'
      - 'CONTRIBUTING.md'
      - 'LICENSE'
      - 'README.md'
      - 'ROADMAP.md'

  workflow_dispatch:

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
      - name: Check out the repo
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: 21
          distribution: temurin

      - name: Validate Gradle wrapper
        uses: gradle/actions/wrapper-validation@v3

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v3

      - name: Compile the project
        run: ./gradlew build -x check

      - name: Checks that sourcecode satisfies formatting rules
        run: ./gradlew spotlessCheck

      - name: Run the unit tests
        run: ./gradlew test

      - name: Run the integration tests
        run: ./gradlew integrationTest

      - name: Kover coverage report
        run: ./gradlew web:koverXmlReport

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v3
        if: github.ref_name == 'main'
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          fail_ci_if_error: true
          verbose: true

  docker:
    runs-on: ubuntu-22.04
    needs: build
    if: github.ref_name == 'main'

    steps:
      - name: Check out the repo
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: 21
          distribution: temurin

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v3

      - name: Build the container image
        run: ./gradlew bootBuildImage

      - name: Start containers
        run: docker compose -f "docker-compose.yml" up -d

      - name: List running containers
        run: docker ps

      - name: Stop containers
        if: always()
        run: docker compose down
