name: CI with Gradle
on: push

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
      - name: Check out the repo
        uses: actions/checkout@v2

      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Validate Gradle Wrapper
        uses: gradle/wrapper-validation-action@v1

      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2

      - name: Compile the project
        uses: gradle/gradle-build-action@v2
        with:
          arguments: build -x check

      - name: Checks that sourcecode satisfies formatting rules
        uses: gradle/gradle-build-action@v2
        with:
          arguments: spotlessCheck

      - name: Run the unit tests
        uses: gradle/gradle-build-action@v2
        with:
          arguments: test

      - name: Run the integration tests
        uses: gradle/gradle-build-action@v2
        with:
          arguments: integrationTest

  docker:
      runs-on: ubuntu-22.04
      needs: build
      if: github.ref_name == 'main'

      steps:
          - name: Check out the repo
            uses: actions/checkout@v2

          - name: Set up JDK 17
            uses: actions/setup-java@v2
            with:
                distribution: 'temurin'
                java-version: '17'

          - name: Setup Gradle
            uses: gradle/gradle-build-action@v2

          - name: Build the container image
            uses: gradle/gradle-build-action@v2
            with:
              arguments: bootBuildImage

          - name: Start containers
            run: docker compose -f "docker-compose.yml" up -d

          - name: List running containers
            run: docker ps

          - name: Stop containers
            if: always()
            run: docker compose down
